### PR TITLE
Namespace-qualified keywords

### PR DESCRIPTION
**Pull request by sebastianpoeplau**
This commit adds support for namespaced keywords as parameters.

### CODE REVIEW

**Comment by csummers** [comment]
@sebastianpoeplau This is great stuff!  Thanks for all your work.

I'm pushing towards a 0.5.0 release and I'll likely be including this as-is.  The only real issue I have is the clash with the deep-get syntax, but I'm thinking that HugSQL should yield to the Clojure namespaced keyword  syntax and implement a different syntax for the deep-get feature moving forward.

**Comment by eerohele** [comment]
Support for namespaced keywords would be great. Is there anything blocking this from getting merged?

**Comment by bwalex** [comment]
@csummers - is the clash with the deep-get syntax the reason this wasn't merged? If so, do you have a proposal on how to move forward (e.g. how the deep-get syntax should look like)?

**Comment by csummers** [comment]
@sebastianpoeplau Thank you for this!

I pulled this into another branch to fix some conflicts and add support for the deep-get syntax when namespaced keywords are present.  (I'm not sure what happened with git after I resolved the conflicts (two parent commits?), but the merge doesn't look like it credited you like a normal PR would.  You'll definitely get the mention in the changelog and release announcement.)

This will ship in a 0.5.0 version soon.

**Comment by csummers** [comment]
@sebastianpoeplau Ah, it did credit you in the git log, I just missed it before: https://github.com/layerware/hugsql/commit/abdfd03396353cd325aefac78939c146ca72be2e

Thanks again!

**Comment by sebastianpoeplau** [comment]
@csummers thanks for merging!

**Pull request closed without merging**
