### PR TITLE
demonstrate #59 'Attempting to call unbound fn'

### PR DESCRIPTION
**Pull request by ryfow**
This reproduces #59 fairly reliably. I don't have a suggestion on how to fix it but thought this might be helpful.

### CODE REVIEW

**Comment by csummers** [comment]
So, this definitely does throw the unbound fn error, but I'm looking at this and thinking "it `ns-umap`s the namespace without re-calling a hugsql-def-* function, so, of course, this fails."  I can understand an issue during startup or reload where the function is not there, but is this test actually demonstrating the same problem as encountered by an app?

**Comment by ryfow** [comment]
This may not be exactly how failure at startup goes, but I think the `hugsql.expr-run` functions that have race conditions are the ones that get generated by the `*-sqlvec` functions, not the `hugsql/def-*` calls. The `def-*` calls shouldn't bump into race-conditions because they're being called in order by `(require)` but the `-sqlvec` calls aren't protected in such a way.

I can try to fiddle with the test enough to only unmap the one var created by the `clj-expr-generic-update-sqlvec` call, but I think the results will be the same.

Notice in the following repl session how a var gets created in run-expr when the sqlvec is created for the first time.

```
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_141-15
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[hugsql.core :as hugsql])
nil
user=> (count (ns-publics 'hugsql.expr-run))
0
user=> (hugsql/def-sqlvec-fns "hugsql/sql/test.sql")
nil
user=> (count (ns-publics 'hugsql.expr-run))
7
user=> (clj-expr-generic-update-sqlvec {:table "test" :updates {:name "X"} :id 1})
["update test set\nname = ?\nwhere id = ?" "X" 1]
user=> (count (ns-publics 'hugsql.expr-run))
8
```

**Comment by ryfow** [comment]
I just change the test locally to not do the `ns-unmap`s. It doesn't fail as reliably, but it does fail with the same error message about 50% of the time when I run with `lein test hugsql.unbound-fn`.

**Comment by csummers** [comment]
You are right!  ns-unmap or not, it should work.

2c61459 should fix this.

**Comment by ryfow** [comment]
Awesome, thanks!

**Pull request merged**
