### PR TITLE
Update hugsql-postgres-async link in docs

### PR DESCRIPTION
**Pull request by dhruvbhatia**

### CODE REVIEW

**Comment by csummers** [comment]
@dhruvbhatia This was already fixed a few days ago.

**Comment by dhruvbhatia** [comment]
Ok thanks - closing!

**Comment by csummers** [comment]
No, actually only one of the links was fixed!  Thanks for the fix.

**Comment by csummers** [comment]
This has now been pushed to the docs site.  Thanks again!

**Comment by dhruvbhatia** [comment]
Thanks - happy to help! :+1:

**Pull request merged**
