### PR TITLE
Preserve file/line metadata from parsed SQL and attach to vars.

### LINKED ISSUE #77: Hugsql-generated functions lack file/line metadata
The biggest complaint I've heard from people I've talked to who use hugsql is that jump-to-definition functions stop working as soon as they hit a hugsql-generated function.

It looks like hugsql uses a `source-logging-push-back-reader` which is capable of tracking line numbers and filenames. Attaching this metadata to the vars created by hugsql would allow existing tooling to be able to jump straight to the `.sql` files from which they are defined.

### PR DESCRIPTION
**Pull request by technomancy**
Fixes #77.

### CODE REVIEW

**Comment by technomancy** [comment]
This allows the `M-.` command in Monroe and Cider (and probably all other editors) to work on hugsql-defined functions.

**Comment by technomancy** [comment]
Amended the commit to include functions generated by `def-sqlvec-fns` as well as `def-db-fns`.

**Comment by technomancy** [comment]
Hi, does this look like a good change?

**Comment by bostonaholic** [comment]
This would be awesome! Being able to "jump to definition" to hugsql functions would be amazing.

**Comment by csummers** [comment]
@technomancy Thanks!

I wasn't seeing your initial commit giving me accurate line results, but this spurred on a way for me to get there.  I've adjusted it to provide the line starting at the hugsql header (usually `:name`).  I think the previous functionality was hindered by getting the line number after already reading the sql.  By changing this to encountering a hugsql header section, we can have the starting line number.  I also added and fixed up some tests.

This seems to be working well for me in Emacs w/ Cider.  I haven't used Monroe before.  I'm hoping that this will pave the way for Cursive support, too.

**Pull request merged**
